### PR TITLE
[DEV-196706] Set Chrome as browser to open the CCT

### PR DESCRIPTION
**Pull request by andresguedes**
Add Chrome package name to open CustomTabs, even Chrome is not the default browser in the device settings.

### CODE REVIEW

**Review by pedroabdenor — APPROVED** [review]
👍

**Review by marcosrivereto — APPROVED** [review]
👍

**Review by lukevance — APPROVED** [review]
I don't think this requires a review on my part, but everything looks good!

Please remember to create a release and include the packaged files for download after this is merged!

**Comment by rodrigosouzatrustly** [comment]
Validated

**Pull request merged**
